version: '2'
services:
  redis:
    image: redis
    restart: always
  mongo:
    image: mongo
    restart: always
  web:
    image: node:6
    working_dir: /app
    entrypoint: 'node index.js'
    links:
      - mongo
      - redis
    volumes:
      - './:/app'
    ports:
      - "8080:8080"
    environment: 
      REDIS_HOST: 'redis'
  runner:
    image: node:6
    working_dir: /app
    entrypoint: 'node engine/runner/start.js'
    links:
      - mongo
      - redis
    volumes:
      - './:/app'
    environment: 
      REDIS_HOST: 'redis'
